//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPDOTNETSession.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int book_id { get; set; }
        public string bookname { get; set; }
        public string author { get; set; }
        public string publisher { get; set; }
        public string ISBN { get; set; }
    }
}
