//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPDOTNETSession.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public int class_id { get; set; }
        public string classname { get; set; }
        public Nullable<int> capacity { get; set; }
        public string classlocation { get; set; }
    }
}
