//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionFilters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarID { get; set; }
        public string CarManufacturer { get; set; }
        public string carColour { get; set; }
        public int numberOfSeats { get; set; }
        public string carSize { get; set; }
        public string carType { get; set; }
        public Nullable<int> RentaCar_rentACarID { get; set; }
    
        public virtual RentaCar RentaCar { get; set; }
    }
}
