//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionFilters.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentACarEntities1 : DbContext
    {
        public RentACarEntities1()
            : base("name=RentACarEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<MiniBu> MiniBus { get; set; }
        public virtual DbSet<RentaCar> RentaCars { get; set; }
        public virtual DbSet<RentAMiniBu> RentAMiniBus { get; set; }
        public virtual DbSet<RentAVan> RentAVans { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Van> Vans { get; set; }
    }
}
