//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionFilters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiniBu
    {
        public int MinibusID { get; set; }
        public string regNumber { get; set; }
        public string MiniBusColour { get; set; }
        public string miniBusManufacturer { get; set; }
        public int numberOfSeats { get; set; }
        public string miniBusSize { get; set; }
        public Nullable<int> RentAMiniBus_RentAMiniBusID { get; set; }
    
        public virtual RentAMiniBu RentAMiniBu { get; set; }
    }
}
