//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionFilters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentAMiniBu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentAMiniBu()
        {
            this.MiniBus = new HashSet<MiniBu>();
        }
    
        public int RentAMiniBusID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string emailAddess { get; set; }
        public System.DateTime hireDate { get; set; }
        public string phoneNumber { get; set; }
        public int MinibusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiniBu> MiniBus { get; set; }
    }
}
