//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionFilters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentaCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentaCar()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int rentACarID { get; set; }
        public string firstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public System.DateTime hireDate { get; set; }
        public int CarID { get; set; }
        public string duration { get; set; }
        public string emailAddress { get; set; }
        public int phoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Cars { get; set; }
    }
}
