//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionFilters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentAVan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentAVan()
        {
            this.Vans = new HashSet<Van>();
        }
    
        public int RentAVanID { get; set; }
        public int vanID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string duation { get; set; }
        public System.DateTime HireDate { get; set; }
        public string EmailAddress { get; set; }
        public string phoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Van> Vans { get; set; }
    }
}
