//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionFilters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Van
    {
        public int vanID { get; set; }
        public string regNumber { get; set; }
        public string vanColour { get; set; }
        public string vanManufacturer { get; set; }
        public string vanSize { get; set; }
        public int numberOfSeats { get; set; }
        public Nullable<int> RentAVan_RentAVanID { get; set; }
    
        public virtual RentAVan RentAVan { get; set; }
    }
}
